name: Settlers of Catan
main: com.DefPdeW.SettlersOfCatan.SettlersOfCatan
version: 1.0
commands:
   join:
      description: Join the game
      usage: /<command> [color]
      permission: <plugin name>.basic
      permission-message: You don't have <permission>