name: Settlers of Catan
main: com.Pulsior.SettlersOfCatan.SettlersOfCatan
version: 1.0
commands:
   join:
      description: Join the game
      usage: /<command> [color] (red, blue, green or black)
      permission: <plugin name>.basic
      permission-message: You don't have <permission>
   check:
      description: Debug command
      usage: /<command>
      permission: <plugin name>.basic
      permission-message: You don't have <permission>
   buy:
      description: Buy a settlement, road or city with your resources
      usage: /<command> [whatever you want to buy]
      permission: <plugin name>.basic
      permission-message: You don't have <permission>
   newgame:
      description: Start a new Settlers of Catan game
      usage: /<command>
      permission: <plugin name>.basic
      permission-message: You don't have <permission>
   launchgame:
      description: Start playing!
      usage: /<command>
      permission: <plugin name>.basic
      permission-message: You don't have <permission>
      aliases: launch
   endturn:
      description: End your turn and allow someone else to play
      usage: /<command>
      permission: <plugin name>.basic
      permission-message: You don't have <permission>
   save:
      description: Save the game to play another day
      usage: /<command>
      permission: <plugin name>.basic
      permission-message: You don't have <permission>
   load:
      description: Load a saved game
      permission: <plugin name>.basic
      permission-message: You don't have <permission>

      